// Simulated agentic file-building for the Delivery tab.
//
// THIS IS THE ONLY STUBBED SEAM. The to-do pool itself is real (served by
// GET /api/qa/delivery). What's faked here is the agent that DRAFTS and ITERATES
// files once a to-do is delegated — drafting latency, versioned filenames, and
// applying feedback. When the real file-building agent lands, replace these two
// helpers with API calls (e.g. POST /api/qa/delivery/{id}/draft and
// /api/qa/delivery/{id}/iterate) and delete the timers — the DeliveryTab UI and
// its state machine stay exactly the same.

export interface DeliveryFile {
  name: string;
  version: number;
  content: string; // real text so the file can be downloaded + attached
}

// Either a to-do or a suggestion — both delegate the same way.
type Delegable = { title: string; askDraft?: string };

// The user can ask Indigo Iota to revise a file this many times (v1 … v5).
export const MAX_ITERATIONS = 5;

// Simulated agent latency (ms) — long enough to show the "drafting…" state.
const DRAFT_MS = 1300;
const ITERATE_MS = 1200;

function stem(title: string): string {
  const slug = title
    .trim()
    .split(/\s+/)
    .slice(0, 3)
    .join("_")
    .replace(/[^A-Za-z0-9_]/g, "");
  return slug || "Document";
}

function wait<T>(value: T, ms: number): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

// Illustrative document body so there's a real file to download/attach. The real
// agent will replace this with a generated .docx; the UI flow stays identical.
function buildContent(todo: Delegable, version: number): string {
  return (
    `${todo.title}\n` +
    `${"=".repeat(todo.title.length)}\n\n` +
    `${(todo.askDraft || "").trim()}\n\n` +
    `— Draft v${version}, generated by Indigo Iota (illustrative content for this phase).`
  );
}

/** STUB — draft the first version of an item's file. */
export function draftFile(todo: Delegable): Promise<DeliveryFile> {
  return wait(
    { name: `${stem(todo.title)}_v1.docx`, version: 1, content: buildContent(todo, 1) },
    DRAFT_MS,
  );
}

/** STUB — apply feedback and produce the next version (v2 … v5). */
export function iterateFile(
  todo: Delegable,
  files: DeliveryFile[],
): Promise<DeliveryFile> {
  const next = (files.length ? Math.max(...files.map((f) => f.version)) : 0) + 1;
  return wait(
    {
      name: `${stem(todo.title)}_v${next}.docx`,
      version: next,
      content: buildContent(todo, next),
    },
    ITERATE_MS,
  );
}

/** Download a generated file locally so the user can attach it to an email. */
export function downloadFile(file: DeliveryFile): void {
  const blob = new Blob([file.content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = file.name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
